name: CI/CD for Docker Compose Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 80:80
          - 8000:8000
          - 3000:3000
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./Django
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build and push web service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web:latest ./astro
          docker push ${{ secrets.DOCKER_USERNAME }}/web:latest

      - name: Build and push nginx service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:latest -f ./nginx.Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest

      - name: Start Docker Compose services
        run: |
          docker-compose up -d
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run tests
        run: |

          # curl http://localhost:3000 以验证 web 服务是否正常运行
          curl http://localhost:3000
          curl http://localhost:8000/api/posts/
