name: CI/CD for Docker Compose Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 80:80
          - 8000:8000
          - 3000:3000
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build multi-arch backend service image
        uses: docker/build-push-action@v2
        with:
          context: ./Django
          file: ./Django/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest
          platforms: linux/amd64,linux/arm64
          load: true

      - name: Build multi-arch web service image
        uses: docker/build-push-action@v2
        with:
          context: ./astro
          file: ./astro/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/web:latest
          platforms: linux/amd64,linux/arm64
          load: true

      - name: Build multi-arch nginx service image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./nginx.Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx:latest
          platforms: linux/amd64,linux/arm64
          load: true

      - name: Start Docker Compose services
        run: docker-compose up

      - name: Wait for services to be up
        run: |
          echo "Waiting for services to be up..."
          sleep 5

      - name: Run tests
        run: |
          curl -f http://localhost:3000
          curl -f http://localhost:8000/api/posts/
          curl -f http://localhost:3000/posts/1

      - name: Push backend service image
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Push web service image
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/web:latest

      - name: Push nginx service image
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest